### ISSUE TITLE
screenshot?

### ISSUE THREAD

**Issue by r-lyeh** [bclucas/Alloy-Graphics-Library#2]
took me a while to compile & create a screenshot, for the curious ppl :)

![image](https://cloud.githubusercontent.com/assets/878187/10250945/0f5239f0-692e-11e5-9cbe-d27daa9b5cba.png)

**Comment by bclucas** [comment]
Thanks! I'm going to build a better example app (s) once i'm a little more confident in the infrastructure, but if you encountered any issues with building the project, I would appreciate hearing about them.
Cheers,
 - Blake

**Comment by r-lyeh** [comment]
Sure. For some reason, MSVC got many troubles when differentiating between
initializer lists and new c++11 constructors so I had to disambiguate most
of them.
Would you like me to fork and push, so you can see all differences?

2015-10-03 5:50 GMT+02:00 Blake Lucas <notifications@github.com>:

**Comment by bclucas** [comment]
Yes I would. The full C++11 standard wasn't supported by MSVC until VS2013, but there are enough people using VS2012 that I should make sure it's backward compatible.
